openapi: "3.1.0"
info:
  title: AIXM Model
  version: "1.0"
  description: |
    Minimal model of AIXM features to support the IWXXM model.
    Some detail is given for validation of JSON examples.

components:
  schemas:
    Unit:
      description: AIXM Unit Feature.
      type: object
      required:
        - name
        - type
        - designator
      properties:
        name:
          type: string
        type:
          type: string
        designator:
          type: string

    Airspace:
      description: AIXM Airspace Feature.
      type: object
      required:
        - name
        - type
        - designator
      properties:
        name:
          type: string
        type:
          type: string
        designator:
          type: string

    AirspaceLayer:
      description: AIXM Airspace Layer Feature.
      type: object

    AirspaceVolume:
      description: AIXM Airspace Volume Feature.
      type: object

    AirportHeliport:
      description: AIXM Airport/Heliport feature.
      type: object
      required:
        - name
        - type
        - designator
      properties:
        name:
          type: string
        type:
          type: string
        designator:
          type: string

    RunwayDirection:
      description: An AIXM RunwayDirection Feature.
      type: string
      pattern: "^[0-9]{2}[LCR]?$"

    ValDistanceVertical:
      description: AIXM ValDistanceVerticalType

    CodeVerticalReferenceBase:
      description: AIXM CodeVerticalReferenceBaseType
      type: object

    CodeValueInterrpetationBase:
      description: AIXM CodeValueInterrpetationBaseType
      type: object

    ValDistanceVerticalBase:
      description: AIXM ValDistanceVerticalBaseType
      type: object
