openapi: "3.1.0"
info:
  title: IWXXM Report Model
  version: "1.0"
  description: Minimal model of AIXM features to support IWXXM model.

components:
  schemas:
    Unit:
      type: object
      required:
      - name
      - type
      - designator
      properties:
        name:
          type: string
        type:
          type: string
        designator:
          type: string

    Airspace:
      description: An AIXM airspace feature.
      type: object
      required:
      - name
      - type
      - designator
      properties:
        name:
          type: string
        type:
          type: string
        designator:
          type: string

    AirspaceLayer:
      type: string

    AirspaceVolume:
      type: string

    AirportHeliport:
      description: An AIXM airport/heliport feature.
      type: string
      pattern: "^[A-Z]{4}$"

    Runway:
      type: string

    RunwayDirection:
      description: An AIXM runway direction feature.
      type: string
      pattern: "^[0-9]{2}[LCR]?$"

    ValDistanceVertical:
      type: string

    CodeVerticalReferenceBase:
      description: TODO
      type: object

    CodeValueInterrpetationBase:
      description: TODO
      type: object

    ValDistanceVerticalBase:
      description: TODO
      type: object

    UomDistanceVertical:
      description: TODO
      type: object