openapi: "3.1.0"
info:
  title: AIXM Model
  version: "1.0"
  description: |
    Minimal model of AIXM features to support the IWXXM model.
    Some detail is given for validation of JSON examples.

components:
  schemas:
    Unit:
      description: AIXM Unit Feature.
      type: object
      required:
        - type
      properties:
        name:
          type: string
        type:
          type: string
        designator:
          type: string

    Airspace:
      description: AIXM Airspace Feature.
      type: object
      required:
        - name
        - type
        - designator
      properties:
        name:
          type: string
        type:
          type: string
        designator:
          type: string

    AirspaceLayer:
      description: AIXM Airspace Layer Feature.
      type: object

    AirspaceVolume:
      description: AIXM Airspace Volume Feature.
      type: object
      properties:
        upperLimit:
          $ref: "#/components/schemas/ValDistanceVertical"
        upperLimitReference:
          $ref: "#/components/schemas/CodeVerticalReferenceBase"
        lowerLimit:
          $ref: "#/components/schemas/ValDistanceVertical"
        lowerLimitReference:
          $ref: "#/components/schemas/CodeVerticalReferenceBase"
        "horizontalProjection":
          description: A list of latitude/longitude pairs.
          type: array
          minItems: 6
          items:
            type: number

    AirportHeliport:
      description: AIXM Airport/Heliport feature.
      type: object
      required:
        - designator
      properties:
        designator:
          type: string

    RunwayDirection:
      description: An AIXM RunwayDirection Feature.
      type: object
      required:
        - designator
      properties:
        designator:
          type: string

    ValDistanceVertical:
      description: AIXM ValDistanceVertical
      allOf:
        - $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Measure"
        - $ref: "#/components/schemas/UomDistanceVertical"

    UomDistanceVertical:
      description: Unit of measure for ValDistanceVertical.
      type: string
      enum: ["FT", "M", "FL", "SM", "OTHER"]

    CodeVerticalReferenceBase:
      description: AIXM CodeVerticalReferenceBaseType
      type: string
      enum: ["SFC", "MSL", "W84", "STD", "OTHER"]

    CodeValueInterrpetationBase:
      description: AIXM CodeValueInterrpetationBaseType
      type: string
      enum: ["ABOVE", "AT_OR_ABOVE", "AT_OR_BELOW", "BELOW", "OTHER"]

    Temperature:
      description: Temperature value.
      allOf:
        - $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Measure"
        - $ref: "#/components/schemas/UomTemperature"

    UomTemperature:
      description: Unit of measure for temperature.
      type: object
      required:
        - uom
      properties:
        uom:
          type: string

    Pressure:
      description: Temperature value.
      allOf:
        - $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Measure"
        - $ref: "#/components/schemas/UomPressure"

    UomPressure:
      description: Unit of measure for pressure.
      type: object
      required:
        - uom
      properties:
        uom:
          type: string

    Density:
      description: Density value.
      allOf:
        - $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Measure"
        - $ref: "#/components/schemas/UomDensity"

    UomDensity:
      description: Unit of measure for density.
      type: object
      required:
        - uom
      properties:
        uom:
          type: string

    NilReason:
      description: Nil object with optional reason for nil value.
      type: object
      required:
        - nil
      properties:
        nil:
          type: boolean
        reason:
          type: string

    Any:
      description: A type that can represent any object.
