openapi: "3.1.0"
info:
  title: IWXXM Space Weather Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Space Weather diagram.

components:
  schemas:
    SpaceWeatherAdvisory:
      description: An advisory of space weather conditions of significance to aviation as represented in ICAO Annex 3 and PANS-MET (Doc 10157).
      allOf:
        - $ref: "../Common/Report.yaml#/components/schemas/Report"
        - type: object
          required:
            - issueTime
            - issuingSpaceWeatherCentre
          properties:
            issueTime:
              $ref: "../GML/GML.yaml#/components/schemas/TimeInstant"
            issuingSpaceWeatherCentre:
              $ref: "../AIXM/AIXM.yaml#/components/schemas/Unit"
            advisoryNumber:
              $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            replacedAdvisoryNumber:
              type: array
              maxItems: 4
              uniqueItems: true
              items:
                $ref: "../Common/String.yaml#/components/schemas/CharacterString"
            effect:
              type: array
              uniqueItems: true
              items:
                $ref: "#/components/schemas/SpaceWeatherEffect"
            analysis:
              type: array
              maxItems: 5
              uniqueItems: true
              items:
                $ref: "Space_Weather_Analysis.yaml#/components/schemas/SpaceWeatherAnalysis"
            remarks:
              $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            nextAdvisoryTime:
              $ref: "../GML/GML.yaml#/components/schemas/TimeInstant"

    SpaceWeatherEffect:
      description: Effect of the space weather phenomena.
      type: string
      enum: ["HF_COM", "SATCOM", "GNSS", "RADIATION"]
