openapi: "3.1.0"
info:
  title: IWXXM Space Weather Analysis Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Space Weather Analysis diagram.

components:
  schemas:
    SpaceWeatherAnalysis:
      description: Observed or forecast space weather phenomena.
      type: object
      required:
        - phenomenonTime
        - intensityAndRegion
        - timeIndicator
      properties:
        phenomenonTime:
          description: The time at which meteorological phenomena occur.
          $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"
        intensityAndRegion:
          description: Container of intensity of the space weather phenomena and affected region(s).
          type: array
          minItems: 1
          uniqueItems: true
          items:
            $ref: "#/components/schemas/SpaceWeatherIntensityAndRegion"
        timeIndicator:
          description: Indicator of observed or forecast conditions.
          $ref: "../Common/Time_Indicator.yaml#/components/schemas/TimeIndicator"

    SpaceWeatherIntensityAndRegion:
      description: Container of space weather intensity and affected region(s).
      type: object
      required:
        - intensity
        - region
      properties:
        intensity:
          description: Intensity of the space weather phenomena.
          $ref: "#/components/schemas/SpaceWeatherIntensity"
        region:
          description: Region affected by the space weather phenomena.
          type: array
          minItems: 1
          uniqueItems: true
          items:
            $ref: "#/components/schemas/SpaceWeatherRegion"

    SpaceWeatherIntensity:
      description: Intensity of the space weather phenomena.
      type: string
      enum: ["MOD", "SEV"]

    SpaceWeatherRegion:
      description: Affected region described in coordinates and textual description (if applicable), as well as altitude (radiation events only).
      type: object
      required:
        - location
        - locationIndicator
      properties:
        location:
          description: The geographic location at which space weather phenomena occur.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceVolume"
        locationIndicator:
          description: The geographic area code, such as high northern latitudes.
          type: array
          minItems: 1
          maxItems: 6
          uniqueItems: true
          items:
            $ref: "#/components/schemas/SpaceWeatherLocation"

    SpaceWeatherLocation:
      description: Coverage affected by space weather phenomenon.
      type: string
      enum: ["HNH", "MNH", "EQN", "EQS", "MSH", "HSH", "DAYSIDE", "NIGHTSIDE"]
