openapi: "3.1.0"
info:
  title: IWXXM TAF Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM TAF diagram.

components:
  schemas:
    MeteorologicalAerodromeForecast:
      type: object
      required:
        - phenomenonTime
      properties:
        phenomenonTime:
          $ref: "../GML/GML.yaml#/components/schemas/TimePeriod"
        prevailingVisibility:
          $ref: "../GML/GML.yaml#/components/schemas/Length"
        prevailingVisibilityOperator:
          $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
        surfaceWind:
          $ref: "../Common/Surface_Wind.yaml#/components/schemas/AerodromeSurfaceWindForecast"
        weather:
          type: array
          maxItems: 3
          uniqueItems: true
          items:
            $ref: "../Common/Weather.yaml#/components/schemas/AerodromeForecastWeather"
        cloud:
          $ref: "../Common/Cloud.yaml#/components/schemas/AerodromeCloudForecast"
        temperature:
          type: array
          maxItems: 2
          uniqueItems: true
          items:
            $ref: "#/components/schemas/AerodromeAirTemperatureForecast"
        changeIndicator:
          $ref: "#/components/schemas/AerodromeForecastChangeIndicator"
        cloudAndVisibilityOK:
          type: string
          enum: ["CAVOK"]

    AerodromeAirTemperatureForecast:
      type: object
      required:
        - maximumAirTemperature
        - maximumAirTemperatureTime
        - minimumAirTemperature
        - minimumAirTemperatureTime
      properties:
        maximumAirTemperature:
          $ref: "../GML/GML.yaml#/components/schemas/Measure"
        maximumAirTemperatureTime:
          $ref: "../GML/GML.yaml#/components/schemas/TimeInstant"
        minimumAirTemperature:
          $ref: "../GML/GML.yaml#/components/schemas/Measure"
        minimumAirTemperatureTime:
          $ref: "../GML/GML.yaml#/components/schemas/TimeInstant"

    AerodromeForecastChangeIndicator:
      type: string
      enum:
        [
          "BECOMING",
          "TEMPORARY_FLUCTUATIONS",
          "FROM",
          "PROBABILITY_30",
          "PROBABILITY_30_TEMPORARY_FLUCTUATIONS",
          "PROBABILITY_40",
          "PROBABILITY_40_TEMPORARY_FLUCTUATIONS",
        ]
