openapi: "3.1.0"
info:
  title: IWXXM WAFS Meteorological Phenomenon Property Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Meteorological Phenomenon Property diagram.

components:
  schemas:
    WAFSJetStreamWindSymbol:
      type: object
      required:
        - location
        - windSpeed
      properties:
        location:
          $ref: "../Meteorological_Feature/Geometry_Types.yaml#/components/schemas/ElevatedPoint"
        windSpeed:
          $ref: "../Common/Measure.yaml#/components/schemas/VelocityWithNilReason"
        IsotachUpperElevation:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVerticalBase"
        IsotachUpperVerticalReference:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
        IsotachLowerElevation:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVerticalBase"
        IsotachLowerVerticalReference:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"

    RadiationIncident:
      required:
        - siteName
        - incidentTime
      properties:
        siteName:
          $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
        incidentTime:
          $ref: "../GML/GML.yaml#/components/schemas/TimeInstant"

    DegreeOfTurbulence:
      description: |
        See the Manual on Codes (WMO No. 306), Vol I.2 FM 94 BUFR Code table 0 11 030 "Extended Degree of Turbulence".
        http://codes.wmo.int/bufr4/codeflag/0-11-030
      type: string
      enum: []

    DegreeOfIcing:
      description: |
        See the Manual on Codes (WMO No. 306), Vol I.2 FM 94 BUFR Code table 0 20 041 "Airframe Icing".
        http://codes.wmo.int/bufr4/codeflag/0-20-041
      type: string
      enum: []

    CloudDistribution:
      description:
        See the Manual on Codes (WMO No. 306), Vol I.2 FM 94 BUFR Code table 0 20 008 "Cloud Distribution for Aviation".
        http://codes.wmo.int/bufr4/codeflag/0-20-008
      type: string
      enum: []

    CloudType:
      description: |
        See the Manual on Codes (WMO No. 306), Vol I.2 FM 94 BUFR Code table 0 20 012 "Cloud Type".
        http://codes.wmo.int/bufr4/codeflag/0-20-012
      type: string
      enum: []
