openapi: "3.1.0"
info:
  title: IWXXM WAFS Meteorological Phenomenon Property Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Meteorological Phenomenon Property diagram.

components:
  schemas:
    WAFSJetStreamWindSymbol:
      description: Describes the horizontal wind speed and direction at the point and optionally the elevation of the 80kt isotach below and above the maximum wind speed level if available.
      type: object
      required:
        - location
        - windSpeed
      properties:
        location:
          description: Position of the wind symbol.
          $ref: "../Meteorological_Feature/Geometry_Types.yaml#/components/schemas/ElevatedPoint"
        windSpeed:
          description: Horizontal wind speed at the indicated position.
          $ref: "../Common/Measure.yaml#/components/schemas/VelocityWithNilReason"
        IsotachUpperElevation:
          description: The vertical distance of the 80 knot isotach above the jet stream measured from vertical reference.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVertical"
        IsotachUpperVerticalReference:
          description: A code indicating the reference for a vertical distance.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
        IsotachLowerElevation:
          description: The vertical distance of the 80 knot isotach below the jet stream measured from vertical reference.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVertical"
        IsotachLowerVerticalReference:
          description: A code indicating the reference for a vertical distance.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"

    RadiationIncident:
      description: A radiation incident characterised by the location name and incident time.
      required:
        - siteName
        - incidentTime
      properties:
        siteName:
          description: Incident location.
          $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
        incidentTime:
          description: Incident time.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimeInstant"

    DegreeOfTurbulence:
      description: |
        Degree of turbulence.
        http://codes.wmo.int/bufr4/codeflag/0-11-030
      type: string
      enum: []

    DegreeOfIcing:
      description: |
        Degree of Icing.
        http://codes.wmo.int/bufr4/codeflag/0-20-041
      type: string
      enum: []

    CloudDistribution:
      description: |
        Cloud distribution.
        http://codes.wmo.int/bufr4/codeflag/0-20-008
      type: string
      enum: []

    CloudType:
      description: |
        Cloud type.
        http://codes.wmo.int/bufr4/codeflag/0-20-012
      type: string
      enum: []
