openapi: "3.1.0"
info:
  title: IWXXM WAFS Meteorological Phenomenon Property Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Meteorological Phenomenon Property diagram.

components:
  schemas:
    WAFSJetStreamWindSymbol:
      type: object
      required:
        - location
        - windSpeed
      properties:
        location:
          $ref: "../Meteorological_Feature/Basic_Types.yaml#/components/schemas/ElevatedPoint"
        windSpeed:
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/VelocityWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        IsotachUpperElevation:
          oneOf:
            - $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVerticalBase"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        IsotachUpperVerticalReference:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
        IsotachLowerElevation:
          oneOf:
            - $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVerticalBase"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        IsotachLowerVerticalReference:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"

    Volcano:
      oneOf:
        - $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
        - $ref: "../Common/Common.yaml#/components/schemas/Nil"

    TropicalCyclone:
      oneOf:
        - $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
        - $ref: "../Common/Common.yaml#/components/schemas/Nil"

    RadiationIncident:
      required:
        - siteName
        - incidentTime
      properties:
        siteName:
          oneOf:
            - $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        incidentTime:
          $ref: "../GML/GML.yaml#/components/schemas/TimeInstant"

    DegreeOfTurbulence:
      description: http://codes.wmo.int/bufr4/codeflag/0-11-030
      type: string
      enum: []

    DegreeOfIcing:
      description: http://codes.wmo.int/bufr4/codeflag/0-20-041
      type: string
      enum: []

    CloudDistribution:
      description: http://codes.wmo.int/bufr4/codeflag/0-20-008
      type: string
      enum: []

    CloudType:
      description: http://codes.wmo.int/bufr4/codeflag/0-20-012
      type: string
      enum: []
