openapi: "3.1.0"
info:
  title: IWXXM WAFS Significant Weather Forecast Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM WAFS Significant Weather Forecast diagram.

components:
  schemas:
    WAFSSignificantWeatherForecast:
      description: Forecasts of significant en-route weather phenomena provided by the World Area Forecast System (WAFS).
      oneOf:
        - $ref: "../Meteorological_Feature/Meteorological_Feature_and_Collection.yaml#/components/schemas/MeteorologicalFeatureCollection"

    WorldAreaForecastCentre:
      description: WorldAreaForecastCentre identifies the institution that creates the report.
      type: string
      enum: ["Washington", "London"]
