openapi: "3.1.0"
info:
  title: IWXXM VONA Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Meteorological Feature Property diagram.

components:
  schemas:
    ResuspendedVolcanicAsh:
      description: Re-suspended volcanic ash.
      type: object
      required:
        - height
      properties:
        height:
          description: Average height of re-suspended volcanic ash field.
          $ref: "../Meteorological_Feature/Geometry_Types.yaml#/components/schemas/ElevatedLevel"

    VolcanicAshCloudVerticalExtent:
      description: Volcanic ash cloud vertical extent.
      type: object
      required:
        - heightSource
        - movement
      properties:
        heightSource:
          description: Source of height data (e.g. ground observer, air-report, radar, LIDAR, satellite, webcam, etc.).
          $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
        movement:
          description: Direction of movement of the observed cloud.
          $ref: "#/components/schemas/VolcanicAshCloudMovement"

    VolcanicAshCloudMovement:
      description: Volcanic ash cloud movement.
      type: string
      enum:
        [
          "N",
          "NE",
          "E",
          "SE",
          "S",
          "SW",
          "W",
          "NW",
          "VERTICAL",
          "OBSCURED",
          "UNKNOWN",
        ]
