openapi: "3.1.0"
info:
  title: IWXXM Volcanic Ash Advisory Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Volcanic Ash Advisory diagram.

components:
  schemas:
    VolcanicAshAdvisory:
      description: An advisory of volcanic ash conditions of significance to aviation as represented in ICAO Annex 3 and PANS-MET (Doc 10157).
      allOf:
        - $ref: "../Common/Report.yaml#/components/schemas/Report"
        - type: object
          required:
            - issueTime
            - issuingVolcanicAshAdvisoryCentre
          properties:
            issueTime:
              $ref: "../GML/GML.yaml#/components/schemas/TimeInstant"
            issuingVolcanicAshAdvisoryCentre:
              $ref: "../AIXM/AIXM.yaml#/components/schemas/Unit"
            volcano:
              $ref: "../Meteorological_Feature/Property_Types.yaml#/components/schemas/Volcano"
            stateOrRegion:
              $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            sourceElevantionAMSL:
              $ref: "../Common/Measure.yaml#/components/schemas/DistanceWithNilReason"
            advisoryNumber:
              $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            informationSource:
              $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            eruptionDetails:
              $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            observation:
              $ref: "Volcanic_Ash_Observed_Conditions.yaml#/components/schemas/VolcanicAshObservedOrEstimatedConditions"
            forecast:
              type: array
              items:
                $ref: "Volcanic_Ash_Forecast_Conditions.yaml#/components/schemas/VolcanicAshForecastConditions"
            remarks:
              $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            nextAdvisoryTime:
              $ref: "../GML/GML.yaml#/components/schemas/TimeInstant"