openapi: "3.1.0"
info:
  title: IWXXM Volcanic Ash Observed Conditions Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Volcanic Ash Observed Conditions diagram.

components:
  schemas:
    VolcanicAshObservedOrEstimatedConditions:
      description: Observed (or estimated) conditions of volcanic ash clouds.
      type: object
      required:
        - phenomenonTime
        - status
      properties:
        phenomenonTime:
          description: The day and time (in UTC) of observation (or estimation) of volcanic ash.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/DateTimeOrPeriod"
        wind:
          description: Wind information to be provided when volcanic ash is not identifiable from satellite data.
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/WindObservedOrEstimated"
        ashCloud:
          description: Information on the volcanic ash cloud.
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/VolcanicAshCloudObservedOrEstimated"
        isEstimated:
          description: Indicates whether the characteristics of the phenomenon is observed (empty or false) or estimated (true).
          type: boolean
        status:
          description: Volcanic ash observation (or estimation) status.
          $ref: "#/components/schemas/VolcanicAshObservedOrEstimatedStatus"

    VolcanicAshCloudObservedOrEstimated:
      description: An observed or estimated volcanic ash cloud, including a horizontal and vertical extent, as well as the speed and direction of motion.
      type: object
      required:
        - ashCloudExtent
        - directionOfMotion
        - speedOfMotion
      properties:
        ashCloudExtent:
          description: The horizontal and vertical extent of the ash cloud.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceVolume"
        directionOfMotion:
          description: The direction of movement of the ash cloud.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Angle"
        speedOfMotion:
          description: The speed of motion of the ash cloud.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Velocity"

    WindObservedOrEstimated:
      description: Wind information within a vertical layer to be provided when volcanic ash is not identifiable from satellite data.
      type: object
      required:
        - verticalLayer
        - windSpeed
        - variableWindDirection
      properties:
        verticalLayer:
          description: The vertical layer in terms of flight levels in which wind is provided.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceLayer"
        windDirection:
          description: Wind direction within the layer.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Angle"
        windSpeed:
          description: Wind speed within the layer.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Velocity"
        variableWindDirection:
          description: When true, indicates that the wind direction is variable.
          type: boolean

    VolcanicAshObservedOrEstimatedStatus:
      description: Observed or estimated volcanic ash cloud information status.
      type: string
      enum: ["PROVIDED", "NOT_IDENTIFIABLE", "NOT_AVAIALABLE", "NOT_PROVIDED"]
