openapi: "3.1.0"
info:
  title: IWXXM Volcanic Ash Forecast Conditions Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Volcanic Ash Forecast Conditions diagram.

components:
  schemas:
    VolcanicAshForecastConditions:
      description: Forecast conditions of volcanic ash clouds.
      type: object
      required:
        - phenomenonTime
        - status
      properties:
        phenomenonTime:
          $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"
        ashCloud:
          type: array
          items:
            $ref: "#/components/schemas/VolcanicAshCloudForecast"
        status:
          $ref: "#/components/schemas/VolcanicAshCloudForecastStatus"

    VolcanicAshCloudForecast:
      description: A forecast volcanic ash cloud, including a horizontal and vertical extent.
      type: object
      required:
        - ashCloudExtent
      properties:
        ashCloudExtent:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceVolume"

    VolcanicAshCloudForecastStatus:
      description: The volcanic ash cloud forecast status indicates the condition other than providing a valid forecast of the volcanic ash cloud.
      type: string
      enum:
        [
          "PROVIDED",
          "NO_VOLCANIC_ASH_EXPECTED",
          "NOT_AVAILABLE",
          "NOT_PROVIDED",
        ]
