openapi: "3.1.0"
info:
  title: IWXXM Volcanic Ash Observed Conditions Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Volcanic Ash Observed Conditions diagram.

components:
  schemas:
    VolcanicAshObservedOrEstimatedConditions:
      description: Observed (or estimated) conditions of volcanic ash clouds.
      type: object
      required:
        - phenomenonTime
        - status
      properties:
        phenomenonTime:
          $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"
        wind:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/WindObservedOrEstimated"
        ashCloud:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/VolcanicAshCloudObservedOrEstimated"
        isEstimated:
          type: string
          enum: ["EST"]
        status:
          $ref: "#/components/schemas/VolcanicAshObservedOrEstimatedStatus"

    VolcanicAshCloudObservedOrEstimated:
      description: An observed or estimated volcanic ash cloud, including a horizontal and vertical extent, as well as the speed and direction of motion.
      type: object
      required:
        - ashCloudExtent
        - directionOfMotion
        - speedOfMotion
      properties:
        ashCloudExtent:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceVolume"
        directionOfMotion:
          $ref: "../GML/GML.yaml#/components/schemas/Angle"
        speedOfMotion:
          $ref: "../GML/GML.yaml#/components/schemas/Velocity"

    WindObservedOrEstimated:
      description: Wind information within a vertical layer to be provided when volcanic ash is not identifiable from satellite data.
      type: object
      required:
        - verticalLayer
        - windSpeed
      properties:
        verticalLayer:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceLayer"
        windDirection:
          $ref: "../GML/GML.yaml#/components/schemas/Angle"
        windSpeed:
          $ref: "../GML/GML.yaml#/components/schemas/Velocity"
        variableWindDirection:
          type: string
          enum: ["VRB"]

    VolcanicAshObservedOrEstimatedStatus:
      description: Observed or estimated volcanic ash cloud information status. .
      type: string
      enum: ["PROVIDED", "NOT_IDENTIFIABLE", "NOT_AVAIALABLE", "NOT_PROVIDED"]
