openapi: "3.1.0"
info:
  title: IWXXM Measure Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Measure diagram.

components:
  schemas:
    PressureWithNilReason:
      description:
      oneOf:
        - $ref: "../Meteorological_Feature/Code_Tables.yaml#/components/schemas/NilReason"
        - $ref: "../GML/GML.yaml#/components/schemas/Pressure"

    TemperatureWithNilReason:
      description:
      oneOf:
        - $ref: "../Meteorological_Feature/Code_Tables.yaml#/components/schemas/NilReason"
        - $ref: "../GML/GML.yaml#/components/schemas/Temperature"

    AngleWithNilReason:
      description:
      oneOf:
        - $ref: "../Meteorological_Feature/Code_Tables.yaml#/components/schemas/NilReason"
        - $ref: "../GML/GML.yaml#/components/schemas/Angle"

    VelocityWithNilReason:
      description:
      oneOf:
        - $ref: "../Meteorological_Feature/Code_Tables.yaml#/components/schemas/NilReason"
        - $ref: "../GML/GML.yaml#/components/schemas/Velocity"

    DistanceWithNilReason:
      description:
      oneOf:
        - $ref: "../Meteorological_Feature/Code_Tables.yaml#/components/schemas/NilReason"
        - $ref: "../GML/GML.yaml#/components/schemas/Length"

    LengthWithNilReason:
      description:
      oneOf:
        - $ref: "../Meteorological_Feature/Code_Tables.yaml#/components/schemas/NilReason"
        - $ref: "../GML/GML.yaml#/components/schemas/Length"

    DateTimeOrPeriodWithNilReason:
      description:
      oneOf:
        - $ref: "../Meteorological_Feature/Code_Tables.yaml#/components/schemas/NilReason"
        - $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"

    AssociationRole:
      description: ????
      type: object
