openapi: "3.1.0"
info:
  title: IWXXM Measure Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Measure diagram.

components:
  schemas:
    AngleWithNilReason:
      description: TO DO
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Angle"
        - $ref: "#/components/schemas/NilReason"

    VelocityWithNilReason:
      description: TO DO
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Speed"
        - $ref: "#/components/schemas/NilReason"

    DistanceWithNilReason:
      description: TO DO
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Length"
        - $ref: "#/components/schemas/NilReason"

    LengthWithNilReason:
      description: TO DO
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Length"
        - $ref: "#/components/schemas/NilReason"

    MeasureWithNilReason:
      description: TO DO
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Measure"
        - $ref: "#/components/schemas/NilReason"

    NilReason:
      type: object
      properties:
        nilReason:
          $ref: "../GML/GML.yaml#/components/schemas/NilReason"
