openapi: "3.1.0"
info:
  title: IWXXM Code Tables Model
  version: "1.0"

components:
  schemas:
    MeteorologicalPhenomenon:
      description: |
        MeteorologicalFeatures identifies the indicated meteorological phenomenon.
        http://codes.wmo.int/bufr4/codeflag/0-08-011
      type: string
      enum: []
