openapi: "3.1.0"
info:
  title: IWXXM Code Tables Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Code Tables diagram.

components:
  schemas:
    MeteorologicalPhenomenon:
      description: |
        MeteorologicalPhenomenon identifies the indicated meteorological phenomenon.
        http://codes.wmo.int/bufr4/codeflag/0-08-011
      type: string
      enum: []
