openapi: "3.1.0"
info:
  title: IWXXM Geometry Types Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Geometry Types diagram.

components:
  schemas:
    ElevatedPoint:
      description: Describes a 3 dimensional point in terms of a horizontal position and an elevation, the latter of which can be expressed in metrics commonly used in the aviation domain.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Point"
        - type: object
          required:
            - elevation
          properties:
            elevation:
              description: The vertical distance of the point measured from the vertical reference.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVertical"
            verticalReference:
              description: A code indicating the reference for a vertical distance.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
            interpretation:
              description: A code indicating how a value needs to be interpreted when used as a filter or condition.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeValueInterrpetationBase"

    ElevatedEnvelope:
      description: Describes a 3 dimensional envelope in terms of a horizontal area and an elevation, the latter of which can be expressed in metrics commonly used in the aviation domain.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Envelope"
        - type: object
          required:
            - upperElevation
            - lowerElevation
          properties:
            upperElevation:
              description: The vertical distance of the upper surface measured from the vertical reference.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVertical"
            upperVerticalReference:
              description: A code indicating the reference for a vertical distance.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
            lowerElevation:
              description: The vertical distance of the lower surface measured from the vertical reference.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVertical"
            lowerVerticalReference:
              description: A code indicating the reference for a vertical distance.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"

    ElevatedLevel:
      description: Describes a vertical level in terms of an elevation which can be expressed in metrics commonly used in the aviation domain.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/GeometricPrimitive"
        - type: object
          required:
            - elevation
          properties:
            elevation:
              description: The vertical distance of the curve measured from the vertical reference.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVertical"
            verticalReference:
              description: A code indicating the reference for a vertical distance.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
            interpretation:
              description: A code indicating how a value needs to be interpreted when used as a filter or condition.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeValueInterrpetationBase"

    ElevatedCurve:
      description: Describes a horizontal curve in 3 dimensional space in terms of its horizontal position and an elevation, the latter of which can be expressed in metrics commonly used in the aviation domain.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Curve"
        - type: object
          required:
            - elevation
          properties:
            elevation:
              description: The vertical distance of the curve measured from the vertical reference.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVertical"
            verticalReference:
              description: A code indicating the reference for a vertical distance.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
            interpretation:
              description: A code indicating how a value needs to be interpreted when used as a filter or condition.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeValueInterrpetationBase"

    ElevatedSurface:
      description: Describes a horizontal surface in 3 dimensional space in terms of its horizontal position and an elevation, the latter of which can be expressed in metrics commonly used in the aviation domain.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Surface"
        - type: object
          required:
            - elevation
          properties:
            elevation:
              description: The vertical distance of the surface measured from the vertical reference.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVertical"
            verticalReference:
              description: A code indicating the reference for a vertical distance.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
            interpretation:
              description: A code indicating how a value needs to be interpreted when used as a filter or condition.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeValueInterrpetationBase"

    ElevatedVolume:
      description: Describes a 3 dimensional volume in terms of a horizontal area and an elevation, the latter of which can be expressed in metrics commonly used in the aviation domain.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Surface"
        - type: object
          required:
            - upperElevation
            - lowerElevation
          properties:
            upperElevation:
              description: The vertical distance of the upper surface measured from the vertical reference.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVertical"
            upperVerticalReference:
              description: A code indicating the reference for a vertical distance.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
            upperInterpretation:
              description: A code indicating how a value needs to be interpreted when used as a filter or condition.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeValueInterrpetationBase"
            lowerElevation:
              description: The vertical distance of the lower surface measured from the vertical reference.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/ValDistanceVertical"
            lowerVerticalReference:
              description: A code indicating the reference for a vertical distance.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
            lowerInterpretation:
              description: A code indicating how a value needs to be interpreted when used as a filter or condition.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeValueInterrpetationBase"
