openapi: "3.1.0"
info:
  title: IWXXM Meteorological Feature Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Meteorological Featrue and Collection diagram.

components:
  schemas:
    MeteorologicalFeatureCollection:
      description: A collective for meteorological features.
      allOf:
        - $ref: "../Common/Report.yaml#/components/schemas/BasicReport"
        - type: object
          required:
            - issueTime
            - originatingCentre
            - phenomenonCategory
            - feature
          properties:
            boundingPeriod:
              description: The period covering all of the phenomena mentioned in the collective.
              $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimePeriod"
            boundingVolume:
              description: The volume containing all of the phenomena mentioned in the collective during the bounding period.
              $ref: "Geometry_Types.yaml#/components/schemas/ElevatedEnvelope"
            phenomenaList:
              description: List of meteorological phenomena involved in the collection.
              type: array
              uniqueItems: true
              items:
                $ref: "Code_Tables.yaml#/components/schemas/MeteorologicalPhenomenon"
            issueTime:
              description: The time the collective is issued.
              $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimeInstant"
            originatingCentre:
              description: Institution that creates the reports.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/Any"
            phenomenonCategory:
              description: The category of the meteorological phenomenon which is either weatherObservations or weatherForecasts.
              $ref: "#/components/schemas/WMOCategoryCode"
            phenomenonBaseTime:
              description: The data time of the forecast, usually provided to identify different sets of numerical weather prediction product.
              $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimeInstant"
            phenomenonTime:
              description: The time instant or period during which the indicated meteorological phenomenon occurred or is expected to occur.
              $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/DateTimeOrPeriod"
            feature:
              description: Meteorological feature(s) of the collection.
              type: array
              minItems: 1
              uniqueItems: true
              items:
                $ref: "#/components/schemas/MeteorologicalFeature"

    MeteorologicalFeature:
      description: Basic feature for describing a meteorological and related phenomenon.
      type: object
      required:
        - phenomenon
      properties:
        issueTime:
          description: The time the report is issued.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimeInstant"
        originatingCentre:
          description: Institution that creates the reports.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/Any"
        phenomenonBaseTime:
          description: The data time of the forecast, usually provided to identify different sets of numerical weather prediction product.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimeInstant"
        phenomenonCategory:
          description: The category of the meteorological phenomenon which is either weatherObservations or weatherForecasts.
          $ref: "#/components/schemas/WMOCategoryCode"
        phenomenonTime:
          description: The time instant or period during which the indicated meteorological phenomenon occurred or is expected to occur.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/DateTimeOrPeriod"
        phenomenon:
          description: The meteorological phenomenon mentioned in the report.
          $ref: "Code_Tables.yaml#/components/schemas/MeteorologicalPhenomenon"
        phenomenonGeometry:
          description: Geometry of the meteorological phenomenon.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/Any"
        phenomenonProperty:
          description: Properties of the meteorological phenomenon.
          type: array
          uniqueItems: true
          items:
            $ref: "../AIXM/AIXM.yaml#/components/schemas/Any"

    WMOCategoryCode:
      description: Additional topic categories for WMO community.
      type: string
      enum:
        [
          "weatherObservations",
          "weatherForecasts",
          "volcanicObservations",
          "volcanicForecasts",
        ]
