openapi: "3.1.0"
info:
  title: IWXXM Property Types Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Property Types diagram.

components:
  schemas:
    Volcano:
      description: Information of a volcano.
      type: object
      required:
        - name
      properties:
        name:
          description: Name of the Volcano.
          $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
        IAVCEINumber:
          description: International Association of Volcanology and Chemistry of the Earth's Interior (IAVCEI) number of the volcano.
          $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
        sourceElevation:
          description: Elevation of the vent of the volcano from mean sea level.
          $ref: "../Meteorological_Feature/Geometry_Types.yaml#/components/schemas/ElevatedLevel"
        activityStatus:
          description: Description of current activity status of the volcano.
          $ref: "#/components/schemas/VolcanoActivityStatus"
        lastVolcanicAshEmission:
          description: Time of last volcanic ash emission.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimeInstant"
        onsetTime:
          description: Time of onset of eruptive activity.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimeInstant"
        duration:
          description: Duration of volcanic ash producing eruption.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimePeriod"

    TropicalCyclone:
      description: A tropical cyclone.
      type: object
      required:
        - name
      properties:
        name:
          description: Name of the tropical cyclone.
          $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"

    VolcanoActivityStatus:
      description: Volcano activity status.
      type: string
      enum:
        [
          "ERUPTION_OCCURRED",
          "ERUPTION_ONGOING",
          "HEIGHTENED_UNREST",
          "DECREASED_ACTIVITY",
          "UNKNOWN",
          "NIL",
        ]
