openapi: "3.1.0"
info:
  title: IWXXM Report Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Common/Cloud diagram.

components:
  schemas:
    AerodromeCloudForecast:
      type: object
      properties:
        verticalVisibility:
          description: http://codes.wmo.int/common/quantity-kind/verticalVisibility
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/LengthWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        layer:
          type: array
          maxItems: 4
          uniqueItems: true
          items:
            $ref: "#/components/schemas/CloudLayer"

    CloudLayerWithNilReason:
      allOf:
        - $ref: "#/components/schemas/CloudLayer"
        - $ref: "../Measures/Measure.yaml#/components/schemas/NilReason"

    CloudLayer:
      type: object
      required:
        - amount
        - base
      properties:
        amount:
          oneOf:
            - $ref: "#/components/schemas/CloudAmountReportedAtAerodrome"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        base:
          description: http://codes.wmo.int/common/quantity-kind/heightOfBaseOfCloud
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/DistanceWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        cloudType:
          oneOf:
            - $ref: "#/components/schemas/SigConvectiveCloudType"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"

    CloudAmountReportedAtAerodrome:
      description: http://codes.wmo.int/49-2/CloudAmountReportedAtAerodrome
      type: string
      enum: []

    SigConvectiveCloudType:
      description: http://codes.wmo.int/49-2/SigConvectiveCloudType
      type: string
      enum: []
