openapi: "3.1.0"
info:
  title: IWXXM Cloud Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Common/Cloud diagram.

components:
  schemas:
    AerodromeCloudForecast:
      description: Forecast cloud conditions, including predicted vertical visibility and cloud layers.
      type: object
      properties:
        verticalVisibility:
          description: The vertical visibility.  Vertical visibility is defined as the vertical visual range into an obscuring medium.
          $ref: "Measure.yaml#/components/schemas/LengthWithNilReason"
        layer:
          description: Description of individual layer of cloud.
          type: array
          maxItems: 4
          uniqueItems: true
          items:
            $ref: "#/components/schemas/CloudLayer"

    CloudLayer:
      description: A cloud layer, including a cloud amount, cloud base and cloud type.
      type: object
      required:
        - amount
        - base
      properties:
        amount:
          description: The observed cloud amount.
          $ref: "#/components/schemas/CloudAmountReportedAtAerodrome"
        base:
          description: For a given cloud or cloud layer, height of the lowest level in the atmosphere at which the air contains a perceptible quantity of cloud particles.
          $ref: "Measure.yaml#/components/schemas/DistanceWithNilReason"
        cloudType:
          description: The observed significant cloud types - cumulonimbus or towering cumulus.
          $ref: "#/components/schemas/SigConvectiveCloudType"

    CloudAmountReportedAtAerodrome:
      description: |
        Amount of cloud.
        http://codes.wmo.int/49-2/CloudAmountReportedAtAerodrome
      type: string
      enum: []

    SigConvectiveCloudType:
      description: |
        Genus of cloud of operational significance to aviation: significant convective clouds only.
        http://codes.wmo.int/49-2/SigConvectiveCloudType
      type: string
      enum: []
