openapi: "3.1.0"
info:
  title: IWXXM Report Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Common/Cloud diagram.

components:
  schemas:
    AerodromeCloudForecast:
      description: Forecast cloud conditions, including predicted vertical visibility and cloud layers.
      type: object
      properties:
        verticalVisibility:
          description: http://codes.wmo.int/common/quantity-kind/verticalVisibility
          $ref: "Measure.yaml#/components/schemas/LengthWithNilReason"
        layer:
          type: array
          maxItems: 4
          uniqueItems: true
          items:
            $ref: "#/components/schemas/CloudLayer"

    CloudLayer:
      description: A cloud layer, including a cloud amount, cloud base and cloud type.
      type: object
      required:
        - amount
        - base
      properties:
        amount:
          $ref: "#/components/schemas/CloudAmountReportedAtAerodrome"
        base:
          description: http://codes.wmo.int/common/quantity-kind/heightOfBaseOfCloud
          $ref: "Measure.yaml#/components/schemas/DistanceWithNilReason"
        cloudType:
          $ref: "#/components/schemas/SigConvectiveCloudType"

    CloudAmountReportedAtAerodrome:
      description: |
        Amount of cloud.
        http://codes.wmo.int/49-2/CloudAmountReportedAtAerodrome
      type: string
      enum: []

    SigConvectiveCloudType:
      description: |
        Genus of cloud of operational significance to aviation: significant convective clouds only.
        http://codes.wmo.int/49-2/SigConvectiveCloudType
      type: string
      enum: []
