openapi: "3.1.0"
info:
  title: IWXXM Measure Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Measure diagram.

components:
  schemas:
    AngleWithNilReason:
      description: A nillable Angle quantity.
      oneOf:
        - $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Angle"
        - $ref: "../AIXM/AIXM.yaml#/components/schemas/NilReason"

    VelocityWithNilReason:
      description: A nillable Velocity quantity.
      oneOf:
        - $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Velocity"
        - $ref: "../AIXM/AIXM.yaml#/components/schemas/NilReason"

    DistanceWithNilReason:
      description: A nillable Distance quantity.
      oneOf:
        - $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Distance"
        - $ref: "../AIXM/AIXM.yaml#/components/schemas/NilReason"

    LengthWithNilReason:
      description: A nillable Length quantity.
      oneOf:
        - $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Length"
        - $ref: "../AIXM/AIXM.yaml#/components/schemas/NilReason"

    MeasureWithNilReason:
      description: A nillable Measure quantity.
      oneOf:
        - $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Measure"
        - $ref: "../AIXM/AIXM.yaml#/components/schemas/NilReason"
