openapi: "3.1.0"
info:
  title: IWXXM Measure Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Measure diagram.

components:
  schemas:
    AngleWithNilReason:
      description: A nillable Angle quantity.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Angle"
        - $ref: "#/components/schemas/NilReason"

    VelocityWithNilReason:
      description: A nillable Velocity quantity.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Speed"
        - $ref: "#/components/schemas/NilReason"

    DistanceWithNilReason:
      description: A nillable Distance quantity.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Distance"
        - $ref: "#/components/schemas/NilReason"

    LengthWithNilReason:
      description: A nillable Length quantity.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Length"
        - $ref: "#/components/schemas/NilReason"

    MeasureWithNilReason:
      description: A nillable Measure quantity.
      allOf:
        - $ref: "../GML/GML.yaml#/components/schemas/Measure"
        - $ref: "#/components/schemas/NilReason"

    NilReason:
      type: object
      properties:
        nilReason:
          $ref: "../GML/GML.yaml#/components/schemas/NilReason"
