openapi: "3.1.0"
info:
  title: IWXXM Report Model
  version: "1.0"

components:
  schemas:
    PermissibleUsage:
      type: string
      enum: ["OPERATIONAL", "NON-OPERATIONAL"]

    PermissibleUsageReason:
      type: string
      enum: ["TEST", "EXERCISE"]
