openapi: "3.1.0"
info:
  title: IWXXM Report Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Common/Report diagram.

components:
  schemas:
    BasicReport:
      description: The base type for all reports, including information that is common across all report types.
      type: object
      required:
        - reportStatus
        - permissibleUsage
      properties:
        reportStatus:
          $ref: "#/components/schemas/ReportStatus"
        permissibleUsage:
          $ref: "Permissible_Usage.yaml#/components/schemas/PermissibleUsage"
        permissibleUsageReason:
          $ref: "Permissible_Usage.yaml#/components/schemas/PermissibleUsageReason"
        permissibleUsageSupplementary:
          $ref: "String.yaml#/components/schemas/CharacterString"

    ReportStatus:
      type: string
      enum: ["CORRECTION", "AMENDMENT", "NORMAL"]

    Report:
      description: The fundamental type for all legacy reports in Annex 3.
      allOf:
        - $ref: "#/components/schemas/BasicReport"
        - type: object
          properties:
            translatedBulletinID:
              $ref: "String.yaml#/components/schemas/CharacterString"
            translatedBulletinReceptionTime:
              type: string
              format: date-time
            translationCentreDesignator:
              $ref: "String.yaml#/components/schemas/CharacterString"
            translationCentreName:
              $ref: "String.yaml#/components/schemas/CharacterString"
            translationTime:
              type: string
              format: date-time
            translationFailedTAC:
              $ref: "String.yaml#/components/schemas/CharacterString"
