openapi: "3.1.0"
info:
  title: IWXXM String Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Common/String diagram.

components:
  schemas:
    CharacterString:
      description: |
        The following captures the class definition in the IWXXM String diagram.
        It has been simplified to simplify examples while remaining schema compliant.

          type: object
          required:
           - characterSet
           - elements
           - maxLength
           - size
          properties:
           characterSet:
             type: string
             enum: ["ISO 10646-2"]
           elements:
             type: string
          maxLength:
             type: integer
             minimum: 0
           size:
             type: integer
             minimum: 0

      type: string

    StringWithNilReason:
      description: A nillable string quantity. References to this type may be nil and may include a nilReason.
      oneOf:
        - $ref: "#/components/schemas/CharacterString"
        - $ref: "../AIXM/AIXM.yaml#/components/schemas/NilReason"
