openapi: "3.1.0"
info:
  title: Surface Wind
  version: "1.0"

components:
  schemas:
    AerodromeSurfaceWindTrendForecast:
      required:
        - meanWindSpeed
      properties:
        meanWindDirection:
          description: http://codes.wmo.int/common/quantity-kind/windDirection
          $ref: "../GML/GML.yaml#/components/schemas/Angle"
        meanWindSpeed:
          description: http://codes.wmo.int/common/quantity-kind/windSpeed
          $ref: "../GML/GML.yaml#/components/schemas/Speed"
        meanWindSpeedOperator:
          $ref: "Relational_Operator.yaml#/components/schemas/RelationalOperator"
        windGustSpeed:
          description: http://codes.wmo.int/common/quantity-kind/maximumWindGustSpeed
          $ref: "../GML/GML.yaml#/components/schemas/Speed"
        windGustSpeedOperator:
          $ref: "Relational_Operator.yaml#/components/schemas/RelationalOperator"

    AerodromeSurfaceWindForecast:
      allOf:
        - $ref: "#/components/schemas/AerodromeSurfaceWindTrendForecast"
        - type: object
          properties:
            variableWindDirection:
              type: string
              enum: ["VRB"]
