openapi: "3.1.0"
info:
  title: IWXXM AIRMET Analysis Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM AIRMET Analysis diagram.

components:
  schemas:
    AIRMETEvolvingConditionCollection:
      description: A collection of AIRMETEvolvingConditions, each representing a location where AIRMET observed or forecast conditions exist.
      type: object
      required:
        - phenomenonTime
        - timeIndicator
        - member
      properties:
        phenomenonTime:
          description: The time at which meteorological phenomena occur.
          $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"
        member:
          description: The members of this collection.
          type: array
          minItems: 1
          uniqueItems: true
          items:
            $ref: "#/components/schemas/AIRMETEvolvingCondition"
        timeIndicator:
          description: Indication whether the information is observed and expected to continue, or forecast.
          $ref: "../Common/Time_Indicator.yaml#/components/schemas/TimeIndicator"

    AIRMETEvolvingCondition:
      description: Conditions that indicate the presence of a specific AIRMET phenomenon such as mountain obscuration or a thunderstorm, along with expected changes to the phenomena such as intensity, speed, and direction.
      type: object
      required:
        - geometry
      properties:
        geometry:
          description: The expected geographic region(s) affected by the reported phenomenon at a particular time (thunderstorms, volcanic ash, etc.).
          $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceVolume"
        directionOfMotion:
          description: The expected direction of movement of a meteorological condition.
          $ref: "../Common/Measure.yaml#/components/schemas/AngleWithNilReason"
        speedOfMotion:
          description: The expected speed of movement of a meteorological condition.
          $ref: "../GML/GML.yaml#/components/schemas/Velocity"
        intensityChange:
          description: The expected change in intensity for the reported meteorological condition (e.g., intensifying, weakening, or no change) determined at the time of AIRMET analysis based on the current state of the meteorological condition.
          $ref: "#/components/schemas/AIRMETExpectedIntensityChange"
        cloudBase:
          description: The cloud base of reported clouds.
          $ref: "../GML/GML.yaml#/components/schemas/Distance"
        cloudBaseReference:
          description: The reference surface used for the value of the cloud base.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
        cloudTop:
          description: The cloud top of reported clouds.
          $ref: "../GML/GML.yaml#/components/schemas/Distance"
        cloudTopReference:
          description: The reference surface used for the value of the cloud base.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
        cloudTopAbove:
          description: Indicates whether the cloud top is above the reported values.
          type: boolean
        surfaceVisibility:
          description: The surface visibility.
          $ref: "../GML/GML.yaml#/components/schemas/Distance"
        surfaceVisibilityCause:
          description: The weather condition(s) causing reduced visibility.
          $ref: "#/components/schemas/WeatherCausingVisibiltyReduction"
        surfaceWindDirection:
          description: The widespread surface wind direction.
          $ref: "../GML/GML.yaml#/components/schemas/Angle"
        surfaceWindSpeed:
          description: The widespread surface wind speed.
          $ref: "../GML/GML.yaml#/components/schemas/Velocity"
        approximateLocation:
          description: Indicator of whether the location of phenomena is approximate.
          type: boolean

    AIRMETExpectedIntensityChange:
      description: Expected change in intensity for AIRMET phenomena.
      type: string
      enum: ["NO_CHANGE", "WEAKEN", "INTENSIFY"]

    WeatherCausingVisibiltyReduction:
      description: |
        A weather condition reducing visibility, such as dust, rain or volcanic ash.
        http://codes.wmo.int/49-2/WeatherCausingVisibilityReduction
      type: string
      enum: []
