openapi: "3.1.0"
info:
  title: IWXXM AIRMET Analysis Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM AIRMET Analysis diagram.

components:
  schemas:
    AIRMETEvolvingConditionCollection:
      description: A collection of AIRMETEvolvingConditions, each representing a location where AIRMET observed or forecast conditions exist.
      type: object
      required:
        - phenomenonTime
        - timeIndicator
        - member
      properties:
        phenomenonTime:
          $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"
        member:
          type: array
          minItems: 1
          uniqueItems: true
          items:
            $ref: "#/components/schemas/AIRMETEvolvingCondition"
        timeIndicator:
          $ref: "../Common/Time_Indicator.yaml#/components/schemas/TimeIndicator"

    AIRMETEvolvingCondition:
      description: Conditions that indicate the presence of a specific AIRMET phenomenon such as mountain obscuration or a thunderstorm, along with expected changes to the phenomena such as intensity, speed, and direction.
      type: object
      required:
        - geometry
      properties:
        geometry:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceVolume"
        directionOfMotion:
          $ref: "../Common/Measure.yaml#/components/schemas/AngleWithNilReason"
        speedOfMotion:
          $ref: "../GML/GML.yaml#/components/schemas/Velocity"
        intensityChange:
          $ref: "#/components/schemas/AIRMETExpectedIntensityChange"
        cloudBase:
          $ref: "../GML/GML.yaml#/components/schemas/Distance"
        cloudBaseReference:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
        cloudTop:
          $ref: "../GML/GML.yaml#/components/schemas/Distance"
        cloudTopReference:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/CodeVerticalReferenceBase"
        cloudTopAbove:
          type: string
          enum: ["ABV"]
        surfaceVisibility:
          $ref: "../GML/GML.yaml#/components/schemas/Distance"
        surfaceVisibilityCause:
          $ref: "#/components/schemas/WeatherCausingVisibiltyReduction"
        surfaceWindDirection:
          $ref: "../GML/GML.yaml#/components/schemas/Angle"
        surfaceWindSpeed:
          $ref: "../GML/GML.yaml#/components/schemas/Velocity"
        approximateLocation:
          type: string
          enum: ["APPROX"]

    AIRMETExpectedIntensityChange:
      description: Expected change in intensity for AIRMET phenomena.
      type: string
      enum: ["NO_CHANGE", "WEAKEN", "INTENSIFY"]

    WeatherCausingVisibiltyReduction:
      description: |
        A weather condition reducing visibility, such as dust, rain or volcanic ash.

        http://codes.wmo.int/49-2/WeatherCausingVisibilityReduction
      type: string
      enum: []
