openapi: "3.1.0"
info:
  title: IWXXM Tropical Cyclone Advisory Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Tropical Cyclone Observed Conditions diagram.

components:
  schemas:
    TropicalCycloneObservedConditions:
      description: Observed conditions of a tropical cyclone
      type: object
      required:
        - phenomenonTime
        - tropicalCyclonePosition
        - movement
        - intensityChange
        - centralPressure
        - maximumSurfaceWindSpeed
      properties:
        phenomenonTime:
          description: The time at which meteorological phenomena occur.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/DateTimeOrPeriod"
        tropicalCyclonePosition:
          description: The tropical cyclone position.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Point"
        cumulonimbusCloudLocation:
          description: Location of cumulonimbus cloud.
          type: array
          uniqueItems: true
          items:
            $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceVolume"
        movement:
          description: The movement observed for the tropical cyclone.
          $ref: "#/components/schemas/TropicalCycloneMovement"
        movementDirection:
          description: The movement direction observed.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Angle"
        movementSpeed:
          description: The movement speed observed.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Velocity"
        intensityChange:
          description: Changes of maximum surface wind speed at time of observation.
          $ref: "#/components/schemas/TropicalCycloneIntensityChange"
        centralPressure:
          description: The central pressure of the tropical cyclone.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/Pressure"
        maximumSurfaceWindSpeed:
          description: The maximum 10-minute mean surface wind speed near the centre of the tropical cyclone which shall be provided in either two units of measures - "m/s" or "[kn_i]" (knot).
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Velocity"

    TropicalCycloneMovement:
      description: The movement type for a tropical cyclone, either MOVING or STATIONARY.
      type: string
      enum: ["MOVING", "STATIONARY"]

    TropicalCycloneIntensityChange:
      description: Change in intensity at the time of the observation.
      type: string
      enum: ["NO_CHANGE", "WEAKEN", "INTENSIFY"]
