openapi: "3.1.0"
info:
  title: IWXXM Tropical Cyclone Forecast Conditions Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Tropical Cyclone Forecast Conditions diagram.

components:
  schemas:
    TropicalCycloneForecastConditions:
      description: Forecast conditions of a tropical cyclone.
      type: object
      required:
        - phenomenonTime
        - tropicalCyclonePosition
        - maximumSurfaceWindSpeed
      properties:
        phenomenonTime:
          $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"
        tropicalCyclonePosition:
             $ref: "../GML/GML.yaml#/components/schemas/Point"
        maximumSurfaceWindSpeed:
             $ref: "../Common/Measure.yaml#/components/schemas/VelocityWithNilReason"
