openapi: "3.1.0"
info:
  title: IWXXM Tropical Cyclone Advisory Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Tropical Cyclone Advisory diagram.

components:
  schemas:
    TropicalCycloneAdvisory:
      description: An advisory of tropical cyclone conditions of significance to aviation as represented in ICAO Annex 3 and PANS-MET (Doc 10157).
      allOf:
        - $ref: "../Common/Report.yaml#/components/schemas/Report"
        - type: object
          required:
            - issueTime
            - issuingTropicalCycloneAdvisoryCentre
          properties:
            issueTime:
              $ref: "../GML/GML.yaml#/components/schemas/TimeInstant"
            issuingTropicalCycloneAdvisoryCentre:
              $ref: "../AIXM/AIXM.yaml#/components/schemas/Unit"
            tropicalCycloneName:
              $ref: "../Meteorological_Feature/Property_Types.yaml#/components/schemas/TropicalCyclone"
            advisoryNumber:
              $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            observation:
              $ref: "Tropical_Cyclone_Observed_Conditions.yaml#/components/schemas/TropicalCycloneObservedConditions"
            forecast:
              type: array
              uniqueItems: true
              items:
                $ref: "Tropical_Cyclone_Forecast_Conditions.yaml#/components/schemas/TropicalCycloneForecastConditions"
            remarks:
              $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            nextAdvisoryTime:
              $ref: "../GML/GML.yaml#/components/schemas/TimeInstant"
