openapi: "3.1.0"
info:
  title: IWXXM Tropical Cyclone Forecast Conditions Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Tropical Cyclone Forecast Conditions diagram.

components:
  schemas:
    TropicalCycloneForecastConditions:
      description: Forecast conditions of a tropical cyclone.
      type: object
      required:
        - phenomenonTime
        - tropicalCyclonePosition
        - maximumSurfaceWindSpeed
      properties:
        phenomenonTime:
          description: The time at which meteorological phenomena occur.
          $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"
        tropicalCyclonePosition:
          description: The tropical cyclone position.
          $ref: "../GML/GML.yaml#/components/schemas/Point"
        maximumSurfaceWindSpeed:
          description: The maximum 10-minute mean surface wind speed near the centre of the tropical cyclone which shall be provided in either two units of measures - "m/s" or "[kn_i]" (knot).
          $ref: "../Common/Measure.yaml#/components/schemas/VelocityWithNilReason"
