openapi: "3.1.0"
info:
  title: IWXXM Tropical Cyclone Advisory Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM Tropical Cyclone Observed Conditions diagram.

components:
  schemas:
    TropicalCycloneObservedConditions:
      description: Observed conditions of a tropical cyclone
      type: object
      required:
        - phenomenonTime
        - tropicalCyclonePosition
        - movement
        - intensityChange
        - centralPressure
        - maximumSurfaceWindSpeed
      properties:
        phenomenonTime:
          $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"
        tropicalCyclonePosition:
          $ref: "../GML/GML.yaml#/components/schemas/Point"
        cumulonimbusCloudLocation:
          type: array
          uniqueItems: true
          items:
            $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceVolume"
        movement:
          $ref: "#/components/schemas/TropicalCycloneMovement"
        movementDirection:
          $ref: "../GML/GML.yaml#/components/schemas/Angle"
        movementSpeed:
          $ref: "../GML/GML.yaml#/components/schemas/Velocity"
        intensityChange:
          $ref: "#/components/schemas/TropicalCycloneIntensityChange"
        centralPressure:
          $ref: "../GML/GML.yaml#/components/schemas/Measure"
        maximumSurfaceWindSpeed:
          $ref: "../GML/GML.yaml#/components/schemas/Velocity"

    TropicalCycloneMovement:
      description: The movement type for a tropical cyclone, either MOVING or STATIONARY.
      type: string
      enum: ["MOVING", "STATIONARY"]

    TropicalCycloneIntensityChange:
      description: Change in intensity at the time of the observation.
      type: string
      enum: ["NO_CHANGE", "WEAKEN", "INTENSIFY"]
