openapi: "3.1.0"
info:
  title: IWXXM SIGMET Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM SIGMET diagram.

components:
  schemas:
    VolcanicAshSIGMET:
      description: A SIGMET that reports the presence of volcanic ash conditions hazardous to flight.
      allOf:
        - $ref: "#/components/schemas/SIGMET"
        - type: object
          properties:
            eruptingVolcano:
              description: The volcano that is erupting - required in all cases other than cancellations.
              $ref: "../Meteorological_Feature/Property_Types.yaml#/components/schemas/Volcano"
            volcanicAshMovedToFIR:
              description: The FIR to which volcanic ash has moved.  Reported only on SIGMET cancellation reports.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/Airspace"

    TropicalCycloneSIGMET:
      description: A SIGMET that reports the presence of a tropical cyclone conditions.
      allOf:
        - $ref: "#/components/schemas/SIGMET"
        - type: object
          properties:
            supplementaryAnalysisCollection:
              description: Observed and/or forecast conditions of the cumulonimbus clouds associated with a tropical cyclone.
              type: array
              uniqueItems: true
              items:
                $ref: "#/components/schemas/AnalysisAndForecastPositionAnalysis"
            tropicalCyclone:
              description: The tropical cyclone being reported in this SIGMET, required in all cases other than cancellations.
              $ref: "../Meteorological_Feature/Property_Types.yaml#/components/schemas/TropicalCyclone"

    SIGMET:
      description: A SIGMET (significant meteorological) report. SIGMETs report the occurrence and/or expected occurrence of specified en-route weather phenomena which may affect the safety of aircraft operations, and of the development of those phenomena over time.
      allOf:
        - $ref: "../Common/Report.yaml#/components/schemas/Report"
        - type: object
          required:
            - issueTime
            - issuingAirTrafficServicesUnit
            - validPeriod
          properties:
            issueTime:
              description: The time at which this report was issued.
              $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimeInstant"
            issuingAirTrafficServicesUnit:
              description: The ATS unit serving the FIR or CTA to which the SIGMET refers.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/Unit"
            originatingMeteorologicalWatchOffice:
              description: MWO originating this report.
              $ref: "../AIXM/AIXM.yaml#/components/schemas/Unit"
            issuingAirTrafficServicesRegion:
              description: The ATS region (FIR, UIR, CTA, or FIR/UIR).
              $ref: "../AIXM/AIXM.yaml#/components/schemas/Airspace"
            sequenceNumber:
              description: The sequence number of this message.
              $ref: "../Common/String.yaml#/components/schemas/StringWithNilReason"
            validPeriod:
              description: The valid period for the entire report covering all observations and forecast conditions.
              $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimePeriod"
            cancelledReportSequenceNumber:
              description: The sequence number of a previous SIGMET that is cancelled by this SIGMET.
              $ref: "../Common/String.yaml#/components/schemas/CharacterString"
            cancelledReportValidPeriod:
              description: The valid period of a previous SIGMET that is cancelled by this SIGMET.
              $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/TimePeriod"
            phenomenon:
              description: The reported phenomenon, such as thunderstorm, tropical cyclone, icing, mountain wave, etc.
              $ref: "#/components/schemas/AeronauticalSignificantWeatherPhenomenon"
            analysisCollection:
              description: Observed and/or forecast conditions of the phenomenon.
              type: array
              uniqueItems: true
              items:
                $ref: "#/components/schemas/AnalysisAndForecastPositionAnalysis"
            isCancelReport:
              description: Indicates whether the report is a 'CANCELLATION' report (true) which cancels a previously issued report or not (false or empty).
              type: boolean

    AeronauticalSignificantWeatherPhenomenon:
      description: |
        Weather phenomenon of significance to aviation operations; used in SIGMET and AIRMET reports. 
        http://codes.wmo.int/49-2/SigWxPhenomena
      type: string
      enum: []

    AnalysisAndForecastPositionAnalysis:
      description: Conditions observed and/or forecast of the SIGMET phenomenon.
      type: object
      properties:
        analysis:
          description: A SIGMET report may include, at a time instant, a phenomenon covering more than one area within the FIR/UIR/CTA.
          $ref: "SIGMET_Analysis.yaml#/components/schemas/SIGMETEvolvingConditionCollection"
        forecastPositionAnalysis:
          description: A forecast of the phenomenon at a time instant within the valid period.
          $ref: "SIGMET_Forecast_Position_Analysis.yaml#/components/schemas/SIGMETPositionCollection"
