openapi: "3.1.0"
info:
  title: IWXXM SIGMET Analysis Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM SIGMET Analysis diagram.

components:
  schemas:
    SIGMETEvolvingConditionCollection:
      required:
        - phenomenonTime
        - timeIndicator
        - member
      properties:
        phenomenonTime:
          $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"
        member:
          type: array
          minItems: 1
          uniqueItems: true
          items:
            $ref: "#/components/schemas/SIGMETEvolvingCondition"
        timeIndicator:
          $ref: "../Common/Time_Indicator.yaml#/components/schemas/TimeIndicator"

    SIGMETEvolvingCondition:
      required:
        - geometry
      properties:
        tropicalCyclonePosition:
          $ref: "../GML/GML.yaml#/components/schemas/Point"
        geometry:
          $ref: "../AIXM/AIXM.yaml#/components/schemas/AirspaceVolume"
        directionOfMotion:
          $ref: "../Common/Measure.yaml#/components/schemas/AngleWithNilReason"
        speedOfMotion:
          $ref: "../GML/GML.yaml#/components/schemas/Velocity"
        intensityChange:
          $ref: "#/components/schemas/SIGMETExpectedIntensityChange"
        approximateLocation:
          type: string
          enum: ["APPROX"]

    SIGMETExpectedIntensityChange:
      type: string
      enum: ["NO_CHANGE", "WEAKEN", "INTENSIFY"]
