openapi: "3.1.0"
info:
  title: IWXXM METAR/SPECI Observation Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM METAR/SPECI Observation diagram.

components:
  schemas:
    MeteorologicalAerodromeObservation:
      description:
      type: object
      required:
        - airTemperature
        - dewpointTemperature
        - qnh
        - surfaceWind
      properties:
        airTemperature:
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/MeasureWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        dewpointTemperature:
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/MeasureWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        qnh:
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/MeasureWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        surfaceWind:
          oneOf:
            - $ref: "#/components/schemas/AerodromeSurfaceWindWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        visibility:
          oneOf:
            - $ref: "#/components/schemas/AerodromeHorizontalVisibilityWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        rvr:
          oneOf:
            - type: array
              maxItems: 4
              uniqueItems: true
              items:
                $ref: "#/components/schemas/AerodromeRunwayVisualRangeWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        presentWeather:
          oneOf:
            - type: array
              maxItems: 3
              uniqueItems: true
              items:
                $ref: "Weather.yaml#/components/schemas/AerodromePresentWeather"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        cloud:
          oneOf:
            - $ref: "#/components/schemas/AerodromeCloudWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        recentWeather:
          oneOf:
            - type: array
              maxItems: 3
              uniqueItems: true
              items:
                $ref: "Weather.yaml#/components/schemas/AerodromeRecentWeather"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        windShear:
          oneOf:
            - $ref: "#/components/schemas/AerodromeWindShear"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        seaCondition:
          oneOf:
            - $ref: "#/components/schemas/AerodromeSeaConditionWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        runwayState:
          oneOf:
            - type: array
              maxItems: 3
              uniqueItems: true
              items:
                $ref: "#/components/schemas/AerodromeRunwayStateWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        cloudAndVisibilityOK:
          type: string
          enum: ["CAVOK"]

    AerodromeSurfaceWindWithNilReason:
      allOf:
        - $ref: "#/components/schemas/AerodromeSurfaceWind"
        - $ref: "../Measures/Measure.yaml#/components/schemas/NilReason"

    AerodromeSurfaceWind:
      description:
      type: object
      required:
        - meanWindSpeed
      properties:
        meanWindDirection:
          description: http://codes.wmo.int/common/quantity-kind/windDirection
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/AngleWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        meanWindSpeed:
          description: http://codes.wmo.int/common/quantity-kind/windSpeed
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/VelocityWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        meanWindSpeedOperator:
          oneOf:
            - $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        windGustSpeed:
          description: http://codes.wmo.int/common/quantity-kind/maximumWindGustSpeed
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/VelocityWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        windGustSpeedOperator:
          oneOf:
            - $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        extremeClockwiseWindDirection:
          description: http://codes.wmo.int/common/quantity-kind/windDirection
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/AngleWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        extremeCounterClockwiseWindDirection:
          description: http://codes.wmo.int/common/quantity-kind/windDirection
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/AngleWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        variableWindDirection:
          type: string
          enum: ["VRB"]

    AerodromeHorizontalVisibilityWithNilReason:
      allOf:
        - $ref: "#/components/schemas/AerodromeHorizontalVisibility"
        - $ref: "../Measures/Measure.yaml#/components/schemas/NilReason"

    AerodromeHorizontalVisibility:
      description:
      type: object
      required:
        - prevailingVisibility
      properties:
        prevailingVisibility:
          description: http://codes.wmo.int/common/quantity-kind/aeronauticalPrevailingHorizontalVisibility
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/DistanceWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        prevailingVisibilityOperator:
          oneOf:
            - $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        minimumVisibility:
          description: http://codes.wmo.int/common/quantity-kind/aeronauticalVisibility
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/DistanceWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        minimumVisibilityDirection:
          desciption: http://codes.wmo.int/common/quantity-kind/aerodromeMinimumVisibilityDirection
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/AngleWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"

    AerodromeRunwayVisualRangeWithNilReason:
      allOf:
        - $ref: "#/components/schemas/AerodromeRunwayVisualRange"
        - $ref: "../Measures/Measure.yaml#/components/schemas/NilReason"

    AerodromeRunwayVisualRange:
      description:
      type: object
      required:
        - runway
        - meanRVR
      properties:
        runway:
          oneOf:
            - $ref: "../AIXM/AIXM.yaml#/components/schemas/RunwayDirection"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        meanRVR:
          description: http://codes.wmo.int/common/quantity-kind/runwayVisualRangeRvr
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/DistanceWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        meamRVROperator:
          oneOf:
            - $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        pastTendency:
          $ref: "#/components/schemas/VisualRangeTendency"

    AerodromeCloudWithNilReason:
      allOf:
        - $ref: "#/components/schemas/AerodromeCloud"
        - $ref: "../Measures/Measure.yaml#/components/schemas/NilReason"

    AerodromeCloud:
      description:
      type: object
      properties:
        verticalVisibility:
          description: http://codes.wmo.int/common/quantity-kind/verticalVisibility
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/LengthWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        layer:
          oneOf:
            - type: array
              maxItems: 4
              uniqueItems: true
              items:
                $ref: "../Common/Cloud.yaml#/components/schemas/CloudLayerWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"

    AerodromeWindShearWithNilReason:
      allOf:
        - $ref: "#/components/schemas/AerodromeWindShear"
        - $ref: "../Measures/Measure.yaml#/components/schemas/NilReason"

    AerodromeWindShear:
      description:
      type: object
      properties:
        runway:
          oneOf:
            - type: array
              uniqueItems: true
              items:
                $ref: "../AIXM/AIXM.yaml#/components/schemas/RunwayDirection"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        allRunways:
          type: string
          enum: ["All"]

    AerodromeSeaConditionWithNilReason:
      allOf:
        - $ref: "#/components/schemas/AerodromeSeaCondition"
        - $ref: "../Measures/Measure.yaml#/components/schemas/NilReason"

    AerodromeSeaCondition:
      description:
      type: object
      required:
        - seaSurfaceTemperature
      properties:
        seaSurfaceTemperature:
          description: http://codes.wmo.int/common/quantity-kind/seaSurfaceTemperature
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/MeasureWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        significantWaveHeight:
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/DistanceWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        seaState:
          oneOf:
            - $ref: "Runway_State.yaml#/components/schemas/SeaSurfaceState"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"

    AerodromeRunwayStateWithNilReason:
      allOf:
        - $ref: "#/components/schemas/AerodromeRunwayState"
        - $ref: "../Measures/Measure.yaml#/components/schemas/NilReason"

    AerodromeRunwayState:
      type: object
      properties:
        runway:
          oneOf:
            - $ref: "../AIXM/AIXM.yaml#/components/schemas/RunwayDirection"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        depositType:
          oneOf:
            - $ref: "Runway_State.yaml#/components/schemas/RunwayDeposits"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        contamination:
          oneOf:
            - $ref: "Runway_State.yaml#/components/schemas/RunwayContamination"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        depthOfDeposit:
          description: http://codes.wmo.int/common/quantity-kind/depthOfRunwayDeposit
          oneOf:
            - $ref: "../Measures/Measure.yaml#/components/schemas/DistanceWithNilReason"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        estimatedSurfaceFrictionOrBrakingAction:
          oneOf:
            - $ref: "Runway_State.yaml#/components/schemas/RunwayFrictionCoefficient"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        allRunways:
          type: string
          enum: ["All"]
        cleared:
          type: string
          enum: ["Cleared"]
        fromPreviousReport:
          type: string
          enum: ["Previous"]

    VisualRangeTendency:
      description:
      type: string
      enum: ["UPWARD", "NO_CHANGE", "DOWNWARD", "MISSING_VALUE"]
