openapi: "3.1.0"
info:
  title: IWXXM METAR/SPECI Observation Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM METAR/SPECI Observation diagram.

components:
  schemas:
    MeteorologicalAerodromeObservation:
      description: Meteorological conditions observed at an aerodrome.
      type: object
      required:
        - airTemperature
        - dewpointTemperature
        - qnh
        - surfaceWind
      properties:
        airTemperature:
          description: The observed air temperature.
          $ref: "../Common/Measure.yaml#/components/schemas/TemperatureWithNilReason"
        dewpointTemperature:
          description: The observed dew point temperature.
          $ref: "../Common/Measure.yaml#/components/schemas/TemperatureWithNilReason"
        qnh:
          description: The observed QNH altimeter setting.
          $ref: "../Common/Measure.yaml#/components/schemas/PressureWithNilReason"
        surfaceWind:
          description: Representative surface wind observations.
          $ref: "#/components/schemas/AerodromeSurfaceWind"
        visibility:
          description: Visibility reported as prevailing visibility or the lowest visibility as appropriate.
          $ref: "#/components/schemas/AerodromeHorizontalVisibility"
        rvr:
          description: RVR conditions are required if horizontal visibility or RVR is less than 1500 meters.
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/AerodromeRunwayVisualRange"
        presentWeather:
          description: When observed, between one and three present weather conditions.
          type: array
          maxItems: 3
          uniqueItems: true
          items:
            $ref: "Weather.yaml#/components/schemas/AerodromePresentWeather"
        cloud:
          description: Observed cloud conditions.
          $ref: "#/components/schemas/AerodromeCloud"
        recentWeather:
          description: Recent weather is one of the recent weather phenomena to be reported as supplementary information.
          type: array
          maxItems: 3
          uniqueItems: true
          items:
            $ref: "Weather.yaml#/components/schemas/AerodromeRecentWeather"
        windShear:
          description: Wind shear is one of the recent weather phenomena to be reported as supplementary information.
          $ref: "#/components/schemas/AerodromeWindShear"
        seaCondition:
          description: Sea surface temperature and state of the sea or significant wave height are recent weather phenomena to be reported as supplementary information.
          $ref: "#/components/schemas/AerodromeSeaCondition"
        cloudAndVisibilityOK:
          description: When true, indicates that the following conditions occur simultaneously at the time of observation (also know as "CAVOK").
          type: boolean

    AerodromeSurfaceWind:
      description: An aggregation of surface wind conditions typically reported together at an aerodrome, including wind direction information, wind speed, and wind gusts.
      type: object
      required:
        - meanWindSpeed
      properties:
        meanWindDirection:
          description: he observed average wind direction from which the wind is blowing over the past ten minutes.  Not reported when winds are variable.
          $ref: "../Common/Measure.yaml#/components/schemas/AngleWithNilReason"
        meanWindSpeed:
          description: The average observed wind speed over the past ten minutes
          $ref: "../Common/Measure.yaml#/components/schemas/VelocityWithNilReason"
        meanWindSpeedOperator:
          description: ndication that the mean wind speed is above or below the reported value.
          $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
        windGustSpeed:
          description: Variations from the mean wind speed (gusts) during the past 10 minutes.
          $ref: "../Common/Measure.yaml#/components/schemas/VelocityWithNilReason"
        windGustSpeedOperator:
          description: Indication that the wind gust speed is above or below the reported value.
          $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
        extremeClockwiseWindDirection:
          description: The extreme clockwise direction from which the wind has varied, inclusive.
          $ref: "../Common/Measure.yaml#/components/schemas/AngleWithNilReason"
        extremeCounterClockwiseWindDirection:
          description: The extreme counter-clockwise direction from which the wind has varied, inclusive.
          $ref: "../Common/Measure.yaml#/components/schemas/AngleWithNilReason"
        variableWindDirection:
          description: When true, indicates that the wind direction is variable.
          type: boolean

    AerodromeHorizontalVisibility:
      description: An aggregation of horizontal visibility conditions typically reported together at an aerodrome, including the prevailing visibility and minimum visibility.
      type: object
      required:
        - prevailingVisibility
      properties:
        prevailingVisibility:
          description: The reported prevailing horizontal visibility at the surface that is representative of the aerodrome.
          $ref: "../Common/Measure.yaml#/components/schemas/DistanceWithNilReason"
        prevailingVisibilityOperator:
          description: The reported relational operator for the prevailing horizontal visibility.
          $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
        minimumVisibility:
          description: hThe minimum observed visibility.
          $ref: "../Common/Measure.yaml#/components/schemas/DistanceWithNilReason"
        minimumVisibilityDirection:
          description: The direction of the minimum visibility relative to the reporting station.
          $ref: "../Common/Measure.yaml#/components/schemas/AngleWithNilReason"

    AerodromeRunwayVisualRange:
      description: An aggregation of runway visual range conditions for a single runway, typically reported together at an aerodrome.
      type: object
      required:
        - runway
        - meanRVR
      properties:
        runway:
          description: The runway to which reported runway visual range information applies.
          $ref: "../AIXM/AIXM.yaml#/components/schemas/RunwayDirection"
        meanRVR:
          description: The mean recent runway visual range value observed.
          $ref: "../Common/Measure.yaml#/components/schemas/DistanceWithNilReason"
        meanRVROperator:
          description: The reported relational operator for the mean RVR.
          $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
        pastTendency:
          description: The runway visual range tendency (up, down, no_change).
          $ref: "#/components/schemas/VisualRangeTendency"

    AerodromeCloud:
      description: An aggregation of observed cloud conditions typically reported together at an aerodrome, including cloud types, cloud layers, and vertical visibility.
      type: object
      properties:
        verticalVisibility:
          description: The reported vertical visibility.  Vertical visibility is defined as the vertical visual range into an obscuring medium.
          $ref: "../Common/Measure.yaml#/components/schemas/LengthWithNilReason"
        layer:
          description: The observed cloud groups, up to four may be included.
          type: array
          maxItems: 4
          uniqueItems: true
          items:
            $ref: "../Common/Cloud.yaml#/components/schemas/CloudLayer"

    AerodromeWindShear:
      description: An aggregation of wind shear conditions typically reported together at an aerodrome, including the set of affected runways.
      type: object
      properties:
        runway:
          description: The specific runway(s) affected by wind shear at this aerodrome.
          type: array
          uniqueItems: true
          items:
            $ref: "../AIXM/AIXM.yaml#/components/schemas/RunwayDirection"
        allRunways:
          description: When true, all runways are observed to have wind shear.
          type: boolean

    AerodromeSeaCondition:
      description: An aggregation of sea state conditions typically reported together at an aerodrome.
      type: object
      required:
        - seaSurfaceTemperature
      properties:
        seaSurfaceTemperature:
          description: The sea-surface temperature observed by aeronautical meteorological stations established on offshore structures in support of helicopter operations.
          $ref: "../Common/Measure.yaml#/components/schemas/TemperatureWithNilReason"
        significantWaveHeight:
          description: The significant wave height observed.
          $ref: "../Common/Measure.yaml#/components/schemas/DistanceWithNilReason"
        seaState:
          description: The state of the sea observed by aeronautical meteorological stations established on offshore structures in support of helicopter operations.
          $ref: "SeaSurface_State.yaml#/components/schemas/SeaSurfaceState"

    VisualRangeTendency:
      description: The tendency of visual range (e.g., upward, downward).
      type: string
      enum: ["UPWARD", "NO_CHANGE", "DOWNWARD", "MISSING_VALUE"]
