openapi: "3.1.0"
info:
  title: IWXXM METAR/SPECI Trend Forecast Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM METAR/SPECI Trend Forecast diagram.

components:
  schemas:
    MeteorologicalAerodromeTrendForecast:
      description: Meteorological conditions for trend forecasting at an aerodrome.
      type: object
      required:
        - phenomenonTime
        - changeIndicator
      properties:
        phenomenonTime:
          description: The time at which meteorological phenomena occur.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/DateTimeOrPeriod"
        timeIndicator:
          description: The human-readable time indicator for this trend forecast.
          $ref: "#/components/schemas/TrendForecastTimeIndicator"
        prevailingVisibility:
          description: The prevailing horizontal visibility reported in a trend forecast.
          $ref: "../ISO_TC211/ISO_TC211.yaml#/components/schemas/Distance"
        prevailingVisibilityOperator:
          description: The reported relational operator for the prevailing horizontal visibility.
          $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
        surfaceWind:
          description: Forecast of surface wind.
          $ref: "../Common/Surface_Wind.yaml#/components/schemas/AerodromeSurfaceWindTrendForecast"
        weather:
          description: Forecast of weather phenomena.
          type: array
          maxItems: 3
          uniqueItems: true
          items:
            $ref: "../Common/Weather.yaml#/components/schemas/AerodromeForecastWeather"
        cloud:
          description: Forecast of cloud.
          $ref: "../Common/Cloud.yaml#/components/schemas/AerodromeCloudForecast"
        changeIndicator:
          description: The change indicator for this trend forecast - becoming, temporary conditions, or no significant change.
          $ref: "#/components/schemas/ForecastChangeIndicator"
        cloudAndVisibilityOK:
          description: When true, indicates that the following conditions occur simultaneously at the time of forecast (also know as "CAVOK").
          type: boolean

    TrendForecastTimeIndicator:
      description: Time indicators for trend forecast conditions.
      type: string
      enum: ["AT", "UNTIL", "FROM", "FROM_UNTIL"]

    ForecastChangeIndicator:
      description: Change qualifier of a trend-type forecast or an aerodrome forecast.
      type: string
      enum: ["BECOMING", "TEMPORARY_FLUCTUATIONS"]
