openapi: "3.1.0"
info:
  title: IWXXM METAR/SPECI Trend Forecast Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM METAR/SPECI Trend Forecast diagram.

components:
  schemas:
    MeteorologicalAerodromeTrendForecast:
      description: A model of an aerodrome trend forecast.
      type: object
      required:
        - phenomenonTime
        - changeIndicator
      properties:
        phenomenonTime:
          $ref: "../GML/GML.yaml#/components/schemas/DateTimeOrPeriod"
        timeIndicator:
          $ref: "#/components/schemas/TrendForecastTimeIndicator"
        prevailingVisibility:
          $ref: "../GML/GML.yaml#/components/schemas/Length"
        prevailingVisibilityOperator:
          $ref: "../Common/Relational_Operator.yaml#/components/schemas/RelationalOperator"
        surfaceWind:
          $ref: "../Common/Surface_Wind.yaml#/components/schemas/AerodromeSurfaceWindTrendForecast"
        weather:
          oneOf:
            - type: array
              maxItems: 3
              uniqueItems: true
              items:
                $ref: "../Common/Weather.yaml#/components/schemas/AerodromeForecastWeather"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        cloud:
          oneOf:
            - $ref: "../Common/Cloud.yaml#/components/schemas/AerodromeCloudForecast"
            - $ref: "../Common/Common.yaml#/components/schemas/Nil"
        changeIndicator:
          $ref: "#/components/schemas/ForecastChangeIndicator"
        cloudAndVisibilityOK:
          type: string
          enum: ["CAVOK"]

    TrendForecastTimeIndicator:
      description:
      type: string
      enum: ["AT", "UNTIL", "FROM", "FROM_UNTIL"]

    ForecastChangeIndicator:
      description:
      type: string
      enum: ["BECOMING", "TEMPORARY_FLUCTUATIONS"]
