openapi: "3.1.0"
info:
  title: IWXXM METAR/SPECI Weather Model
  version: "1.0"
  description: |
    An OpenAPI model of the IWXXM METAR/SPECI Weather diagram.

components:
  schemas:
    AerodromeRecentWeather:
      description: |
        Weather phenomenon of operational significance to aviation observed during the period since the last routine report, or last hour, whichever is shorter, but not at the time of observation.
        http://codes.wmo.int/49-2/AerodromeRecentWeather
      type: string
      enum: []

    AerodromePresentWeather:
      description: |
        The present weather observed at, or in near vicinity of, an aerodrome.
        http://codes.wmo.int/49-2/AerodromePresentOrForecastWeather
      type: string
      enum: []
