openapi: "3.1.0"
info:
  title: IWXXM Report Model
  version: "1.0"
  description: Minimal model of GML features to support IWXXM model.

components:
  schemas:
    Pressure:
      description:
      allOf:
        - $ref: "#/components/schemas/Measure"
        - type: object
          required:
            - uom
          properties:
            uom:
              $ref: "#/components/schemas/UomPressure"

    UomPressure:
      type: string
      enum: ["hPa"]

    Temperature:
      description:
      allOf:
        - $ref: "#/components/schemas/Measure"
        - type: object
          required:
            - uom
          properties:
            uom:
              $ref: "#/components/schemas/UomTemperature"

    UomTemperature:
      type: string
      enum: ["Cel"]

    Angle:
      description:
      allOf:
        - $ref: "#/components/schemas/Measure"
        - type: object
          required:
            - uom
          properties:
            uom:
              $ref: "#/components/schemas/UomAngle"

    UomAngle:
      type: string
      enum: ["deg"]

    Length:
      description:
      allOf:
        - $ref: "#/components/schemas/Measure"
        - type: object
          required:
            - uom
          properties:
            uom:
              $ref: "#/components/schemas/UomLength"

    UomLength:
      type: string
      enum: ["[ft_i]", "m"]

    Velocity:
      description:
      allOf:
        - $ref: "#/components/schemas/Measure"
        - type: object
          required:
            - time
            - distance
            - uom
          properties:
            time:
              $ref: "#/components/schemas/UomTime"
            distance:
              $ref: "#/components/schemas/UomLength"
            uom:
              $ref: "#/components/schemas/UomVelocity"

    UomTime:
      type: string
      enum: []

    UomVelocity:
      type: string
      enum: ["m/s", "[kn_i]"]

    Speed:
      description:
      allOf:
        - $ref: "#/components/schemas/Measure"
        - type: object
          required:
            - uom
          properties:
            uom:
              $ref: "#/components/schemas/UomSpeed"

    UomSpeed:
      type: string
      enum: ["m/s", "[kn_i]"]

    Measure:
      type: object
      required:
        - value
      properties:
        value:
          type: number

    DateTime:
      type: string
      format: date-time

    TimePeriod:
      type: object
      properties:
        beginPosition:
          ref: "#/components/schemas/DateTime"
        endPosition:
          ref: "#/components/schemas/DateTime"

    DateTimeOrPeriod:
      oneOf:
        - ref: "#/components/schemas/DateTime"
        - ref: "#/components/schemas/DateTimeOrPeriod"

    AssociationRole:
      description: ????
      type: object

    NilReason:
      description: ????
      type: object

    AbstractGeometricPrimitive:
      description: ????
      type: object

    Point:
      description: ????
      type: object

    Curve:
      description: ????
      type: object

    Surface:
      description: ????
      type: object

    Envelope:
      description: ????
      type: object