openapi: "3.1.0"
info:
  title: IWXXM Report Model
  version: "1.0"
  description: Minimal model of GML features to support IWXXM model.

components:
  schemas:
    NilReason:
      description: http://schemas.opengis.net/gml/3.2.1/basicTypes.xsd
      type: string
      enum: []

    Angle:
      $ref: "#/components/schemas/Measure"

    Length:
      $ref: "#/components/schemas/Measure"

    Velocity:
      $ref: "#/components/schemas/Measure"

    Speed:
      $ref: "#/components/schemas/Measure"

    Measure:
      type: object
      required:
        - value
        - uom
      properties:
        value:
          type: number
        uom:
          type: string

    TimeInstant:
      type: string
      format: date-time

    TimePeriod:
      type: object
      properties:
        beginPosition:
          ref: "#/components/schemas/DateTime"
        endPosition:
          ref: "#/components/schemas/DateTime"

    DateTimeOrPeriod:
      oneOf:
        - ref: "#/components/schemas/DateTime"
        - ref: "#/components/schemas/DateTimeOrPeriod"

    AssociationRole:
      description: ????
      type: object

    AbstractGeometricPrimitive:
      description: ????
      type: object

    Point:
      description: ????
      type: object

    Curve:
      description: ????
      type: object

    Surface:
      description: ????
      type: object

    Envelope:
      description: ????
      type: object